version: '3'

services:
  crm:
    container_name: crm
    image: pkecastillo/crm-docker:v1.0
    ports:
      - "8088:80"
    volumes:
      - ./crm_data:/var/www/html:rw
volumes:
  crm_data: 
    driver: local